### ISSUE TITLE
Control de importes cobrados

### ISSUE THREAD

**Issue by devragare** [Ariadna-Software/ASW-ArigesMovApi#6]
Hay que controlar que lo cobrado no supera el total de la deuda. Ahora se puede dar el caso.

**Comment by rafaelgr** [comment]
Ahora los importes no actualizan la cabecera. Para obtener el importe cobrado lo que  hay que hacer es sumar los importes de las líneas (scobrolin) a lo que figure ya como cobrado en la scobro.
